# build_runtime.ps1 - Concatenates all runtime headers into single file
# Run from src/core/quark/runtime/ directory
# Output: ../codegen/runtime.hpp

$OutputFile = "../codegen/runtime.hpp"
$IncludeDir = "include/quark"

# Header files in dependency order
$HeaderFiles = @(
    "core/value.hpp",
    "core/constructors.hpp",
    "core/truthy.hpp",
    "ops/arithmetic.hpp",
    "ops/comparison.hpp",
    "ops/logical.hpp",
    "types/list.hpp",
    "types/string.hpp",
    "types/function.hpp",
    "builtins/io.hpp",
    "builtins/conversion.hpp",
    "builtins/math.hpp"
)

# Start with header comment
$Output = @"
// runtime.hpp - Quark Runtime Library (Auto-generated)
// DO NOT EDIT - Generated by build_runtime.ps1
// Regenerate with: cd runtime && pwsh build_runtime.ps1

#ifndef QUARK_RUNTIME_HPP
#define QUARK_RUNTIME_HPP

// Standard library includes
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cctype>
#include <cstdarg>


"@

foreach ($file in $HeaderFiles) {
    $FilePath = Join-Path $IncludeDir $file
    if (Test-Path $FilePath) {
        $Output += "// ============================================================`n"
        $Output += "// $file`n"
        $Output += "// ============================================================`n`n"

        # Read file and filter out include guards and inter-header includes
        $Content = Get-Content $FilePath -Raw

        # Remove include guard #ifndef/#define at start
        $Content = $Content -replace '#ifndef QUARK_\w+_HPP\s*\n#define QUARK_\w+_HPP\s*\n', ''

        # Remove #endif at end
        $Content = $Content -replace '\n#endif\s*//\s*QUARK_\w+_HPP\s*$', ''

        # Remove inter-header includes (they're all bundled together)
        $Content = $Content -replace '#include\s+"[^"]+"\s*\n', ''

        # Remove leading/trailing whitespace
        $Content = $Content.Trim()

        $Output += $Content + "`n`n"
    } else {
        Write-Warning "File not found: $FilePath"
    }
}

$Output += "#endif // QUARK_RUNTIME_HPP`n"

# Write output
Set-Content -Path $OutputFile -Value $Output -NoNewline
Write-Host "Generated $OutputFile"
