#!/bin/bash
# build_runtime.sh - Concatenates all runtime headers into single file

OUTPUT_FILE="../codegen/runtime.hpp"
INCLUDE_DIR="include/quark"

# Header files in dependency order
HEADER_FILES=(
    "core/value.hpp"
    "core/constructors.hpp"
    "core/truthy.hpp"
    "ops/arithmetic.hpp"
    "ops/comparison.hpp"
    "ops/logical.hpp"
    "types/list.hpp"
    "types/string.hpp"
    "types/function.hpp"
    "builtins/io.hpp"
    "builtins/conversion.hpp"
    "builtins/math.hpp"
)

# Start with header comment
cat > "$OUTPUT_FILE" << 'HEADER'
// runtime.hpp - Quark Runtime Library (Auto-generated)
// DO NOT EDIT - Generated by build_runtime.sh
// Regenerate with: cd runtime && bash build_runtime.sh

#ifndef QUARK_RUNTIME_HPP
#define QUARK_RUNTIME_HPP

// Standard library includes
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <cctype>
#include <cstdarg>
#include <algorithm>
#include <vector>


HEADER

# Process each header file
for file in "${HEADER_FILES[@]}"; do
    filepath="$INCLUDE_DIR/$file"
    if [ -f "$filepath" ]; then
        echo "// ============================================================" >> "$OUTPUT_FILE"
        echo "// $file" >> "$OUTPUT_FILE"
        echo "// ============================================================" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        # Read file and filter out include guards and inter-header includes
        sed -e '/^#ifndef QUARK_.*_HPP/d' \
            -e '/^#define QUARK_.*_HPP/d' \
            -e '/^#endif.*QUARK_.*_HPP/d' \
            -e '/^#include\s*".*"/d' \
            "$filepath" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    else
        echo "Warning: File not found: $filepath" >&2
    fi
done

echo "#endif // QUARK_RUNTIME_HPP" >> "$OUTPUT_FILE"
echo "Generated $OUTPUT_FILE"
